name: 🐞 Bug Report
description: Use this template to report a bug in the project
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: input
    id: bug-title
    attributes:
      label: 🐞 Bug Title
      description: A concise summary of the bug
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📌 Description
      description: A clear and detailed description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🖥️ Steps to Reproduce
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 📷 Screenshots / Logs
      description: Add any relevant screenshots or logs
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: 💻 Environment
      description: OS, browser, or app version

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
    validations:
      required: false

  - type: input
    id: related
    attributes:
      label: 🔄 Related Issues

  - type: textarea
    id: fix
    attributes:
      label: 🧪 Suggested Fix or Investigation Areas

  - type: textarea
    id: notes
    attributes:
      label: 📎 Additional Notes
